# tmp path used for file system storage, so the benefit here is that we can keep messages across container restarts
# todo look into configuring maildir so a volume could be created to persist beyond container destruction
version: "3.1"

services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MH_STORAGE: maildir